services:
  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: clickhouse/clickhouse-server:latest-alpine
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - data:/var/lib/clickhouse
      - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml

volumes:
  data:
