services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:16.9-alpine3.21
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volume:/var/lib/postgresql/data
