services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume:/data
