services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
