services:
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "7000:9000"
      - "7001:9001"
    volumes:
      - ./volume:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
